### ISSUE TITLE
Google Drive link is not working

### ISSUE THREAD

**Issue by marksamfd** [sara-zc/cie206-prelab13#1]
Giving me 404 error
![image](https://github.com/sara-zc/cie206-prelab13/assets/62911833/8b5ae1c0-ae00-4667-a571-6ce1bba269aa)

**Comment by sara-zc** [comment]
Sorry about that. I think the folder was moved or deleted from my drive by mistake.

In any case, as explained in the pdf, you'll find the mentioned files inside the _Models_ folder in the example code of this repository. Or you can clone them separately from here: https://github.com/jdanylko/Chart-ASPNETCore/tree/master/ChartExample%2FModels%2FChart

I'll update the link in the pdf as soon as possible ISA. Thank you for submitting an issue!

**Comment by sara-zc** [comment]
Updated the drive link in the pdf and in the README ✅
